version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: electronics
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppass
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-prootpass"]
      interval: 5s
      timeout: 5s
      retries: 10

  apache:
    build: ./apache
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./data/dynamic:/var/www/custom_dynamic:ro
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
    networks:
      - webnet

  nginx:
    image: nginx:stable
    depends_on:
      - apache
    ports:
      - "8080:80"  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./data/static:/var/www/custom_static:ro
    networks:
      - webnet

volumes:
  db_data:

networks:
  webnet:
