events {}
http {
    server {
        listen 80;
        root /srv/www/static;

        location /static/ {
            alias /srv/www/static/;
            expires off;
            add_header Cache-Control "no-store";
        }

        location / {
            proxy_pass http://apache:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Authorization $http_authorization;
        }
    }
}
