FROM php:8.2-apache
RUN apt-get update && \
	apt-get install -y --no-install-recommends libaprutil1-dbd-mysql $PHPIZE_DEPS && \
	pecl install redis && \
	docker-php-ext-enable redis && \
	a2enmod authn_dbd && \
	a2enmod dbd && \
	docker-php-ext-install pdo pdo_mysql && \
	rm -rf /var/lib/apt/lists/*
COPY ./dynamic /srv/www/dynamic
COPY ./storage /srv/www/storage
COPY apache.conf /etc/apache2/sites-enabled/000-default.conf
RUN chown -R www-data:www-data /srv/www/dynamic /srv/www/storage
